{
 "title": "Movie Project",
 "time": { "from": "1974-12-31T23:00:00.000Z", "to": "2019-12-31T23:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Erscheinungsjahr",
    "label": "Erscheinungsjahr:",
    "query": "SELECT ProductionYear FROM Movie"
   }
  ]
 },
 "panels": [
  {
   "title": "Filme nach Kinoeintritten des Jahres $Erscheinungsjahr",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "MovieProject",
     "rawSql": "SELECT Title, TicketsSold AS [Verkaufte Kinoeintritte]  FROM MovieProject.dbo.Movie WHERE ProductionYear = $Erscheinungsjahr"
    }
   ]
  },
  {
   "title": "Komplette Filmliste mit Informationen",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Title AS Filmtitel, (FirstName + ' ' + LastName) AS Regisseur, Designation AS Genre, TicketsSold AS [Verkaufte Tickets], ProductionYear AS Erscheinungsjahr \r\n\tFROM Movie\r\n\tINNER JOIN Director ON Movie.Id = Director.Id - 20000\r\n\tINNER JOIN Genre ON Movie.MovieGenreId = Genre.Id\r\n\tORDER BY Filmtitel;"
    }
   ]
  },
  {
   "title": "Regisseure und deren Anzahl Filme",
   "type": "piechart",
   "description": "Damit nur Regisseure mit mehr als einem Film angezeigt werden, folgendes nach GROUP BY einfügen:\nHAVING COUNT(Id) > 1",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DirectorsId) AS MoviesMade, FirstName, LastName \r\n\tFROM DirectorMovie \r\n\t\tINNER JOIN Director \r\n\t\tON DirectorsId = Director.Id \r\n\tGROUP BY FirstName, LastName \r\nUNION\r\nSELECT 46 AS MoviesMade, 'Others' AS FirstName, '' AS LastName \r\n\tFROM Director\r\n\tORDER BY MoviesMade DESC, FirstName ASC"
    }
   ]
  },
  {
   "title": "Verkaufte Kinoeinritte aller Filme je Jahr",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "dataset": "MovieProject",
     "rawSql": "SELECT CONVERT(date, CONVERT(varchar, ProductionYear)) AS time, SUM(TicketsSold) AS [Totale Kino Eintritte] FROM Movie GROUP BY ProductionYear;"
    }
   ]
  }
 ]
}